// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVdsvQT6gIuoLMPSijEqHTygZBPY6UZ6o',
    appId: '1:259528988373:web:09ee1544aeb5c81dacb45c',
    messagingSenderId: '259528988373',
    projectId: 'jce-pos',
    authDomain: 'jce-pos.firebaseapp.com',
    storageBucket: 'jce-pos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsUXwe-qEwdzyQMlVysoDYuMoumPwlMaM',
    appId: '1:259528988373:android:b3ef9cf40e2ade9eacb45c',
    messagingSenderId: '259528988373',
    projectId: 'jce-pos',
    storageBucket: 'jce-pos.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMMWjYZ60PK5E1Me_OygcxcxmONmyen94',
    appId: '1:259528988373:ios:de706f8745e2a89cacb45c',
    messagingSenderId: '259528988373',
    projectId: 'jce-pos',
    storageBucket: 'jce-pos.firebasestorage.app',
    iosBundleId: 'com.jce.pos',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMMWjYZ60PK5E1Me_OygcxcxmONmyen94',
    appId: '1:259528988373:ios:de706f8745e2a89cacb45c',
    messagingSenderId: '259528988373',
    projectId: 'jce-pos',
    storageBucket: 'jce-pos.firebasestorage.app',
    iosBundleId: 'com.jce.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVdsvQT6gIuoLMPSijEqHTygZBPY6UZ6o',
    appId: '1:259528988373:web:d755e0f136bdc10eacb45c',
    messagingSenderId: '259528988373',
    projectId: 'jce-pos',
    authDomain: 'jce-pos.firebaseapp.com',
    storageBucket: 'jce-pos.firebasestorage.app',
  );
}
